# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the orbs to be used by CircleCI
orbs:
  browser-tools: circleci/browser-tools@1.2
  phpunit: stockfiller/phpunit@1.1.0
  codecov: codecov/codecov@3.2.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-test-codecov:
    docker: # run the steps with Docker
      - image: cimg/php:8.0.14-browsers
    working_directory: ~/wits-overflow
    steps:
      - checkout
      - run: sudo pecl install pcov
      - run: sudo pecl install xdebug
      - run: sudo composer selfupdate
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/caching/)
            - composer-v1-
      - run: composer update # install -n --prefer-dist
      - run: sudo composer dump-autoload -o
      - run:
          name: Upload Coverage To CodeCov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN} -v

workflows:
  test-deploy-workflow:
    jobs:
      - build-test-codecov:
        filters:
          branches:
            only:
              devbackend